language: java
jdk:
- oraclejdk8
services:
- mysql
before_install:
- mysql -uroot -e "grant all on beasiswadb.* to beasiswa@localhost identified by 'beasiswa01'"
- mysql -uroot -e "drop database if exists beasiswadb"
- mysql -uroot -e "create database beasiswadb"

